spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=${SSL_MODE:require}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 300000
