-- Seed default roles (idempotent)
INSERT INTO role (name) VALUES ('ROLE_USER')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name) VALUES ('ROLE_BLOG_EDITOR')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name) VALUES ('ROLE_BLOG_MANAGER')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name) VALUES ('ROLE_ADMIN')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role (name) VALUES ('ROLE_SUPERADMIN')
ON CONFLICT (name) DO NOTHING;
