spring:
  flyway:
    enabled: true
    table: flyway_newsletter_schema_history
    baseline-on-migrate: true
    baseline-version: 999
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=${SSL_MODE:require}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
